### ISSUE TITLE
ANR on Android 8.1 (Vivo) due to transactNative method blocking Main Thread for 4000ms

### ISSUE THREAD

**Issue by shfqtm2** [farimarwat/grizzly#2]
FATAL EXCEPTION: Thread-15
com.farimarwat.grizzly.anrmonitor.AnrMonitorException: Method:transactNative is blocking Main Thread for atleast 4000
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(Binder.java:804)
                                                                                                    	at android.view.IGraphicsStats$Stub$Proxy.requestBufferForProcess(IGraphicsStats.java:93)
                                                                                                    	at android.view.ThreadedRenderer$ProcessInitializer.requestBuffer(ThreadedRenderer.java:986)
                                                                                                    	at android.view.ThreadedRenderer$ProcessInitializer.initGraphicsStats(ThreadedRenderer.java:972)
                                                                                                    	at android.view.ThreadedRenderer$ProcessInitializer.init(ThreadedRenderer.java:955)
                                                                                                    	at android.view.ThreadedRenderer.<init>(ThreadedRenderer.java:391)
                                                                                                    	at android.view.ThreadedRenderer.create(ThreadedRenderer.java:295)
                                                                                                    	at android.view.ViewRootImpl.enableHardwareAcceleration(ViewRootImpl.java:1001)
                                                                                                    	at android.view.ViewRootImpl.setView(ViewRootImpl.java:701)
                                                                                                    	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
                                                                                                    	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
                                                                                                    	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3794)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2971)
                                                                                                    	at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1669)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:192)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6702)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

**Comment by farimarwat** [comment]
You received this report as a fatal exception. This is not an issue with Grizzly itself; however, it is reported by Grizzly.

**Comment by shfqtm2** [comment]
I now understand that the ANR reported by Grizzly was likely due to the device’s performance limitations. The slow processing speed of the device caused the `transactNative` method to exceed the established threshold, leading to the ANR detection.

**Comment by AmolPardeshi99** [comment]
From above discussion looks like the thread is not issue but intended behaviour of the SDK.
